function penalty = penalize_agent(U_param,t)

R       = 3;
epsilon = 10^(-8);

u  = @(y) U(y,U_param);
v  = @(y) V(y,[0;0],U_param);
v1 = @(a,y)a(y);

g = [                                  abs(u(R))-epsilon*abs(u(1));...
                                                             -u(0);...
                                                    v1(v([0;0]),1);...
                                                              u(1);...
                                                   -v1(v([1;0]),1);...
                                                    v1(v([1;0]),1);...
     -(v1(v([1+epsilon/2;0]),1)-v1(v([1-epsilon/2;0]),1))/epsilon];
penalty = 2^t*sum((max(g,0)).^2);