function penalty = penalize_agent(U_param,t)

R       = 4;
epsilon = 10^(-2);

u  = @(y) U(y,exp(U_param));
v  = @(y) V(y,[0;0],exp(U_param));
v1 = @(a,y)a(y);

g = [                  1*(abs(u(R))-epsilon*(abs(u(1)) - epsilon));...
                                                   epsilon.^2-u(0);...
                                                    v1(v([0;0]),1);...
                                                              u(1);...
                                                   -v1(v([1;0]),1);...
                                                    v1(v([1;0]),1);...
     -(v1(v([1+epsilon/2;0]),1)-v1(v([1-epsilon/2;0]),1))/epsilon];
%dev = compare_radial_distribution(observed_cells,exp(U_param));
penalty = 2^(sqrt(t))*sum((max(g,0)).^2);
