cluster = parcluster;
opts    = parforOptions(cluster);
ppool   = parpool(cluster,min(cluster.NumWorkers,feature('numcores')));
wtest   = ['We are currently rocking a parallel pool hosted at '...
            ppool.Cluster.Host ', running ' num2str(ppool.NumWorkers)...
            ' workers having ' num2str(ppool.Cluster.NumThreads)...
            ' thread(s). Available cores are: '...
            num2str(feature('numcores')) '.'];
save('TEST.mat','wtest')